### ISSUE TITLE
Can't find the solutions of the exercise in the book Extending the Linear Model with R

### ISSUE THREAD

**Issue by Dhrunit** [julianfaraway/faraway#1]
Can you help me with where can I find the solutions for the book **_Extending the Linear Model with R_** ? as I am not able to find it in this repository and the preface of the book does say that the solution is available 
![image](https://user-images.githubusercontent.com/55096222/212546445-74821083-a123-46fb-8e65-7fea672c2e52.png)

**Comment by julianfaraway** [comment]
Solutions are available to verified instructors using the textbook.

**Comment by Dhrunit** [comment]
Thanks for your time :)
