### ISSUE TITLE
Possible typo in Page 27 of PRA?

### ISSUE THREAD

**Issue by SantiDu** [julianfaraway/faraway#2]
Sorry, it may or may not be a mistake, and it probably has been mentioned several times by other people. 
It is from page 27 of Practical Regression and Anova:
![image](https://github.com/julianfaraway/faraway/assets/37691563/f76b4234-e27a-4aaa-9eef-675b637ce977)
Perhaps we don't need to divide by (q - p) and (n - q)?

**Comment by julianfaraway** [comment]
Yes - that's correct. We do need the divisors for the F-statistic but not here.

**Comment by SantiDu** [comment]
Thank you.
